-- Migration: Add comments table and update view (ULTRA SAFE VERSION)

-- 1. Cleanup view
DROP VIEW IF EXISTS public.posts_with_likes_count CASCADE;

-- 2. Create tables if not exist
CREATE TABLE IF NOT EXISTS public.comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  post_id UUID REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.saved_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  post_id UUID REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, post_id)
);

-- 3. Enable RLS
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_posts ENABLE ROW LEVEL SECURITY;

-- 4. Create policies safely
DO $$ 
BEGIN
    BEGIN
        CREATE POLICY "Comments are viewable by everyone." ON public.comments FOR SELECT USING (true);
    EXCEPTION WHEN duplicate_object THEN NULL; END;

    BEGIN
        CREATE POLICY "Authenticated users can create comments." ON public.comments FOR INSERT WITH CHECK (auth.uid() = user_id);
    EXCEPTION WHEN duplicate_object THEN NULL; END;

    BEGIN
        CREATE POLICY "Users can delete their own comments." ON public.comments FOR DELETE USING (auth.uid() = user_id);
    EXCEPTION WHEN duplicate_object THEN NULL; END;

    BEGIN
        CREATE POLICY "Users can see their own saved posts." ON public.saved_posts FOR SELECT USING (auth.uid() = user_id);
    EXCEPTION WHEN duplicate_object THEN NULL; END;

    BEGIN
        CREATE POLICY "Users can save posts." ON public.saved_posts FOR INSERT WITH CHECK (auth.uid() = user_id);
    EXCEPTION WHEN duplicate_object THEN NULL; END;

    BEGIN
        CREATE POLICY "Users can unsave posts." ON public.saved_posts FOR DELETE USING (auth.uid() = user_id);
    EXCEPTION WHEN duplicate_object THEN NULL; END;
END $$;

-- 5. Recreate view
CREATE OR REPLACE VIEW public.posts_with_likes_count AS
SELECT
    p.id,
    p.user_id,
    p.image_url,
    p.description,
    p.created_at,
    count(DISTINCT l.id) AS likes_count,
    count(DISTINCT c.id) AS comments_count,
    EXISTS (SELECT 1 FROM public.likes WHERE post_id = p.id AND user_id = auth.uid()) AS is_liked_by_user,
    EXISTS (SELECT 1 FROM public.saved_posts WHERE post_id = p.id AND user_id = auth.uid()) AS is_saved_by_user,
    json_build_object(
        'username', pr.username,
        'profile_pic_url', pr.profile_pic_url
    ) AS profiles
FROM
    public.posts p
LEFT JOIN public.likes l ON p.id = l.post_id
LEFT JOIN public.comments c ON p.id = c.post_id
LEFT JOIN public.profiles pr ON p.user_id = pr.id
GROUP BY p.id, p.user_id, p.image_url, p.description, p.created_at, pr.username, pr.profile_pic_url;
