name: venered_social
description: Aplicación de red social tipo Instagram/Threads en Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # Ajustado para la versión de Dart en Flutter 3.19.x

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.0 # Versión corregida y actualizada
  image_picker: ^1.1.2     # Versión corregida y actualizada

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
