-- Venered Social - Supabase SQL Schema
-- Este script crea todas las tablas, relaciones y políticas de seguridad necesarias para la aplicación.

-- PASO 1: Creación de la tabla de perfiles (profiles)
-- Esta tabla almacena la información pública de los usuarios, extendiendo la tabla auth.users.
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE NOT NULL,
  profile_pic_url TEXT,
  bio TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Comentarios sobre la tabla de perfiles
COMMENT ON TABLE public.profiles IS 'Almacena los perfiles públicos de los usuarios.';
COMMENT ON COLUMN public.profiles.id IS 'Referencia al ID del usuario en la tabla auth.users.';
COMMENT ON COLUMN public.profiles.username IS 'Nombre de usuario público y único.';

-- PASO 2: Habilitar la Seguridad a Nivel de Fila (RLS) para perfiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- PASO 3: Definir Políticas de Seguridad para perfiles
-- Política 1: Los perfiles son públicos y cualquiera puede verlos.
CREATE POLICY "Public profiles are viewable by everyone."
ON public.profiles FOR SELECT
USING (true);

-- Política 2: Los usuarios solo pueden crear un perfil para sí mismos.
CREATE POLICY "Users can insert their own profile."
ON public.profiles FOR INSERT
WITH CHECK (auth.uid() = id);

-- Política 3: Los usuarios solo pueden actualizar su propio perfil.
CREATE POLICY "Users can update own profile."
ON public.profiles FOR UPDATE
USING (auth.uid() = id);

-- PASO 4: Trigger para sincronizar nuevos usuarios
-- Esta función se ejecuta automáticamente cada vez que un nuevo usuario se registra en la aplicación (auth.users).
-- Crea una entrada correspondiente en la tabla public.profiles.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  -- Inserta una nueva fila en public.profiles con el id y un username.
  -- Si el username no se proporciona en los metadatos, se generará uno por defecto usando el ID del usuario.
  INSERT INTO public.profiles (id, username)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'username', 'user-' || new.id::text)
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- El trigger se activa después de cada inserción en la tabla auth.users.
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

----------------------------------------------------------------------------------------------

-- PASO 5: Creación de la tabla de publicaciones (posts)
CREATE TABLE public.posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  image_url TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

COMMENT ON TABLE public.posts IS 'Contiene todas las publicaciones de los usuarios.';

-- PASO 6: Habilitar RLS y definir Políticas para posts
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Posts are viewable by everyone."
ON public.posts FOR SELECT
USING (true);

CREATE POLICY "Authenticated users can create posts."
ON public.posts FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own posts."
ON public.posts FOR DELETE
USING (auth.uid() = user_id);

----------------------------------------------------------------------------------------------

-- PASO 7: Creación de la tabla de "Me Gusta" (likes)
CREATE TABLE public.likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id UUID REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  -- La combinación de post_id y user_id debe ser única para evitar que un usuario dé like dos veces.
  UNIQUE(post_id, user_id)
);

COMMENT ON TABLE public.likes IS 'Registra los "me gusta" que los usuarios dan a las publicaciones.';

-- PASO 8: Habilitar RLS y definir Políticas para likes
ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Likes are viewable by everyone."
ON public.likes FOR SELECT
USING (true);

CREATE POLICY "Authenticated users can like/unlike posts."
ON public.likes FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own likes (unlike)."
ON public.likes FOR DELETE
USING (auth.uid() = user_id);

----------------------------------------------------------------------------------------------

-- PASO 9: Creación de la tabla de seguidores (followers)
CREATE TABLE public.followers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  follower_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL, -- El que sigue
  following_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL, -- El que es seguido
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  -- Un usuario no puede seguir a otro más de una vez.
  UNIQUE(follower_id, following_id)
);

COMMENT ON TABLE public.followers IS 'Almacena las relaciones de seguimiento entre usuarios.';

-- PASO 10: Habilitar RLS y definir Políticas para followers
ALTER TABLE public.followers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Follower relationships are viewable by everyone."
ON public.followers FOR SELECT
USING (true);

CREATE POLICY "Authenticated users can follow/unfollow others."
ON public.followers FOR INSERT
WITH CHECK (auth.uid() = follower_id);

CREATE POLICY "Users can delete their own follow relationships (unfollow)."
ON public.followers FOR DELETE
USING (auth.uid() = follower_id);

----------------------------------------------------------------------------------------------

-- ¡FINALIZADO! Ahora solo falta crear el Bucket de almacenamiento para las imágenes.
-- Ve a Storage -> Create a new bucket -> Nómbralo 'posts_images' y asegúrate de marcarlo como "Public".
