name: Build Venered Social

on:
  push:
    tags:
      - 'v*'
      - '[0-9]*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore Google Services JSON
        run: echo "$GOOGLE_SERVICES_JSON_SECRET" > android/app/google-services.json
        env:
          GOOGLE_SERVICES_JSON_SECRET: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APKs
        run: flutter build apk --release --split-per-abi

      - name: Build App Bundle
        run: flutter build appbundle --release

      - name: Compress APKs
        run: zip -j venered_social_v1.0.zip build/app/outputs/flutter-apk/*.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            venered_social_v1.0.zip
            build/app/outputs/bundle/release/app-release.aab
          name: "Venered Social v1.0 (Oficial)"
          body: "🚀 Lanzamiento oficial de Venered Social."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
