name: Build and Release APK

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout del repositorio
        uses: actions/checkout@v3

      - name: 2. Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 3. Instalar dependencias
        run: flutter pub get

      - name: 4. Compilar APK en modo release
        run: flutter build apk --release

      - name: 5. Crear Release y subir el APK
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
